#!/usr/bin/env python3
"""
Step 26: Generate every number, table and figure the paper cites.

The manuscript in ``Paper/`` does not hard-code empirical results.  This
script reads the pipeline outputs and writes

    Paper/generated/numbers.tex   -- one \\newcommand per reported number
    Paper/generated/tab_*.tex     -- LaTeX table bodies
    Paper/Figures/fig_*.pdf       -- figures referenced by the paper

so that re-running ``python scripts/run_all.py`` regenerates the paper's
content and the text can never drift from the code again (the reason for
the 2026-09 audit; see docs/RESEARCH_AUDIT.md).

Inputs: data/processed/indexed_data.csv, data/processed/cleaning_metadata.json,
config/*.yaml, reports/tables/*.csv (steps 03-25) and reports/pre_audit/*
(outputs of the pipeline before the audit fixes, frozen for comparison).
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from scipy import stats

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.constants import ESG_ENV_COLS, ESG_GOV_COLS, ESG_SOC_COLS  # noqa: E402
from src.utils import get_portfolio_top_n, load_profile_weights  # noqa: E402

TABLES = PROJECT_ROOT / "reports" / "tables"
PRE = PROJECT_ROOT / "reports" / "pre_audit"
PROCESSED = PROJECT_ROOT / "data" / "processed"
PAPER = PROJECT_ROOT / "Paper"
GEN = PAPER / "generated"
FIGS = PAPER / "Figures"

FACTOR_LABELS = {
    "ESG_composite": "ESG composite",
    "E_score": "\\quad E pillar",
    "S_score": "\\quad S pillar",
    "G_score": "\\quad G pillar",
    "ESG_orthogonal": "ESG $\\perp$ other factors",
    "financial_score": "Financial",
    "operational_score": "Operational",
    "risk_adjusted_score": "Risk-adjusted",
    "value_score": "Value",
    "growth_score": "Growth",
    "stability_score": "Stability",
    "market_score": "Market (not weighted)",
    "sector_position": "Sector position",
    "pref_balanced": "Balanced composite",
    "pref_esg_first": "ESG-first composite",
    "pref_financial_first": "Financial-first composite",
    "pref_equal_weight": "Equal-weight composite",
    "pref_balanced_feb2026": "Balanced, Feb-2026 weights",
    "pref_balanced_pre_audit": "Balanced, pre-audit pipeline",
    "ESG_composite_pre_audit": "ESG, pre-audit pipeline",
}

# ESG indicators whose non-imputed values come from the ISS governance
# QualityScores that Yahoo Finance redistributes, versus Yahoo ownership /
# analyst-coverage fields that were mapped onto governance columns.
ISS_COLS = {"board_independence_pct", "exec_comp_esg_linked", "shareholder_rights_score",
            "ethics_compliance_score", "esg_risk_rating"}
OWNERSHIP_COLS = {"tax_transparency_score", "data_privacy_score", "esg_controversy_score"}
# Sign / comparison glyphs that are valid in both text and math mode, so a
# macro such as \HOneEst can be used either in running text or inside $...$.
NEG = r"\ensuremath{-}"
LT = r"\ensuremath{<}"

TIER_ORDER = ["ISS governance score", "Yahoo ownership/coverage field", "SEC XBRL item",
              "Public registry (0/1)", "Financial ratio", "Financial proxy", "Imputed"]


class Macros:
    def __init__(self):
        self.lines = ["% Auto-generated by scripts/26_paper_artifacts.py -- do not edit by hand.",
                      "% Re-run `python scripts/run_all.py` (or this script) to refresh."]
        self.names = set()

    def add(self, name, value, fmt=None):
        if not name.isalpha():
            raise ValueError(f"macro name must be letters only: {name}")
        if name in self.names:
            raise ValueError(f"duplicate macro {name}")
        self.names.add(name)
        if isinstance(value, (float, np.floating)):
            text = (fmt or "{:.3f}").format(value)
            text = text.replace("-", NEG, 1) if text.startswith("-") else text
        else:
            text = str(value)
        self.lines.append(f"\\newcommand{{\\{name}}}{{{text}\\xspace}}")

    def write(self, path):
        path.write_text("\n".join(self.lines) + "\n", encoding="utf-8")


def fnum(x, fmt="{:.3f}"):
    if pd.isna(x):
        return "--"
    s = fmt.format(x)
    return s.replace("-", NEG, 1) if s.startswith("-") else s


def pval(p):
    if pd.isna(p):
        return "--"
    if p < 0.001:
        return LT + "0.001"
    return f"{p:.3f}"


def write_table(name, body):
    (GEN / name).write_text("% Auto-generated by scripts/26_paper_artifacts.py\n" + body, encoding="utf-8")


def read(name, base=TABLES):
    return pd.read_csv(base / name)


# ---------------------------------------------------------------------------
# Sample
# ---------------------------------------------------------------------------
def sample_numbers(M, df, u, cfg):
    meta = json.loads((PROCESSED / "cleaning_metadata.json").read_text(encoding="utf-8"))
    M.add("NScored", len(df))
    M.add("NMid", len(u))
    M.add("NUS", int((u["country"] == "US").sum()))
    M.add("NIndia", int((u["country"] == "India").sum()))
    M.add("NLarge", int(df["is_large_cap_benchmark"].fillna(False).astype(bool).sum()))
    M.add("NSectors", u["sector"].nunique())
    dropped = meta.get("dropped_not_trading_at_snapshot", [])
    M.add("NDroppedNotTrading", len(dropped))
    M.add("DroppedNotTrading", ", ".join(t.replace(".NS", "") for t in dropped))
    M.add("NRawCompanies", len(pd.read_csv(PROJECT_ROOT / "data" / "raw" / "combined_raw.csv", usecols=["ticker"])))
    M.add("SnapshotDate", cfg.get("universe", {}).get("snapshot_date", cfg.get("snapshot_date")))
    oos = cfg.get("oos_evaluation", {})
    M.add("OOSEndDate", oos.get("end_date"))
    fx = cfg["INR_USD"]
    M.add("FXRate", f"{float(fx):.2f}")
    M.add("TopN", get_portfolio_top_n(len(u)))
    port = cfg.get("universe", {}).get("portfolio", {})
    M.add("TopPct", f"{100 * float(port.get('top_pct', 0.07)):.0f}")


def find_fx(cfg):
    """INR_USD may sit at top level or inside a nested block."""
    def walk(d):
        if isinstance(d, dict):
            for k, v in d.items():
                if k == "INR_USD":
                    return v
                r = walk(v)
                if r is not None:
                    return r
        return None
    return walk(cfg)


# ---------------------------------------------------------------------------
# ESG provenance (construct validity)
# ---------------------------------------------------------------------------
def provenance(M, u):
    prov = read("esg_data_provenance.csv").set_index("ticker").reindex(u["ticker"])
    rows, used = [], {}
    for pillar, cols in (("E", ESG_ENV_COLS), ("S", ESG_SOC_COLS), ("G", ESG_GOV_COLS)):
        cells = []
        n_used = 0
        for c in cols:
            if c not in u.columns or u[c].notna().sum() == 0 or u[c].nunique() < 2:
                continue
            n_used += 1
            labels = prov[c] if c in prov.columns else pd.Series("direct_ratio", index=prov.index)
            for lab in labels.fillna("direct_ratio"):
                if lab == "real_yahoo":
                    cells.append("ISS governance score" if c in ISS_COLS else "Yahoo ownership/coverage field")
                elif lab == "real_sec":
                    cells.append("SEC XBRL item")
                elif lab == "real_public_registry":
                    cells.append("Public registry (0/1)")
                elif lab == "direct_ratio":
                    cells.append("Financial ratio")
                elif lab == "financial_proxy":
                    cells.append("Financial proxy")
                else:
                    cells.append("Imputed")
        share = pd.Series(cells).value_counts(normalize=True) * 100
        used[pillar] = n_used
        rows.append((pillar, n_used, len(cols), share))
        M.add(f"NInd{pillar}", n_used)
        M.add(f"NIndDeclared{pillar}", len(cols))
        M.add(f"ProxyShare{pillar}", float(share.get("Financial proxy", 0.0) + share.get("Financial ratio", 0.0)), "{:.0f}")
        M.add(f"ISSShare{pillar}", float(share.get("ISS governance score", 0.0)), "{:.0f}")
    M.add("NIndUsed", sum(used.values()))
    M.add("NIndDeclared", len(ESG_ENV_COLS) + len(ESG_SOC_COLS) + len(ESG_GOV_COLS))
    iss_firms = int((prov[[c for c in ISS_COLS if c in prov]] == "real_yahoo").any(axis=1).sum())
    M.add("NISSFirms", iss_firms)
    M.add("NEPAFirms", int((prov == "real_epa").any(axis=1).sum()))

    M.add("NIndUnused", len(ESG_ENV_COLS) + len(ESG_SOC_COLS) + len(ESG_GOV_COLS) - sum(used.values()))

    # Sources as rows, pillars as columns (fits a single column).
    lines = ["\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
             "Source of cell & E & S & G \\\\", "\\midrule",
             "Indicators used / declared & " + " & ".join(f"{n}/{d}" for _, n, d, _ in rows) + " \\\\",
             "\\midrule"]
    for t in TIER_ORDER:
        vals = []
        for _, _, _, share in rows:
            v = share.get(t, 0.0)
            vals.append("--" if v == 0 else LT + "1" if v < 0.5 else f"{v:.0f}")
        lines.append(f"{t} & " + " & ".join(vals) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_provenance.tex", "\n".join(lines) + "\n")


def esg_redundancy(M, u):
    others = ["financial_score", "operational_score", "risk_adjusted_score", "value_score",
              "growth_score", "stability_score", "market_score"]
    X = np.column_stack([np.ones(len(u))] + [u[c].fillna(u[c].median()) for c in others])
    for col, name in (("ESG_composite", "ESG"), ("E_score", "E"), ("S_score", "S"), ("G_score", "G")):
        y = u[col].fillna(u[col].median()).to_numpy()
        b = np.linalg.lstsq(X, y, rcond=None)[0]
        r2 = 1 - np.var(y - X @ b) / np.var(y)
        M.add(f"RSq{name}", float(r2), "{:.2f}")
    rho = stats.spearmanr(u["ESG_composite"], u["financial_score"])[0]
    M.add("RhoESGFin", float(rho), "{:.2f}")
    for a, b, nm in (("E_score", "S_score", "RhoES"), ("E_score", "G_score", "RhoEG"), ("S_score", "G_score", "RhoSG")):
        M.add(nm, float(stats.spearmanr(u[a], u[b])[0]), "{:.2f}")


# ---------------------------------------------------------------------------
# Factor diagnostics
# ---------------------------------------------------------------------------
def diagnostics(M, u):
    vif = read("vif_multicollinearity.csv")
    M.add("VIFMax", float(vif["VIF"].max()), "{:.2f}")
    M.add("VIFMaxFactor", FACTOR_LABELS.get(vif.loc[vif["VIF"].idxmax(), "factor"], "").replace("\\quad ", ""))
    pre_vif = read("vif_multicollinearity.csv", PRE)
    M.add("VIFMaxPre", float(pre_vif["VIF"].max()), "{:.2f}")

    pca = read("advanced_pca_variance.csv")
    cum = pca["cumulative_variance"].to_numpy()
    M.add("PCAFirstThree", float(100 * cum[2]), "{:.1f}")
    M.add("PCANEighty", int(np.argmax(cum >= 0.80) + 1))

    mono = read("factor_monotonicity_diagnostic.csv")
    pre_mono = read("factor_monotonicity_diagnostic.csv", PRE)
    M.add("MonoPost", int(mono["is_monotonic"].astype(str).eq("True").sum()))
    M.add("MonoPre", int(pre_mono["is_monotonic"].astype(str).eq("True").sum()))
    M.add("MonoTotal", len(mono))

    prc = read("profile_rank_correlation.csv")
    def pr(a, b):
        r = prc[((prc.profile1 == a) & (prc.profile2 == b)) | ((prc.profile1 == b) & (prc.profile2 == a))]
        return float(r["spearman_rank_r"].iloc[0])
    M.add("RhoProfEB", pr("pref_esg_first", "pref_balanced"), "{:.2f}")
    M.add("RhoProfBF", pr("pref_balanced", "pref_financial_first"), "{:.2f}")
    M.add("RhoProfEF", pr("pref_esg_first", "pref_financial_first"), "{:.2f}")
    top_n = get_portfolio_top_n(len(u))
    def overlap(a, b):
        ta = set(u.nlargest(top_n, a)["ticker"])
        tb = set(u.nlargest(top_n, b)["ticker"])
        return len(ta & tb)
    M.add("OverlapEB", overlap("pref_esg_first", "pref_balanced"))
    M.add("OverlapBF", overlap("pref_balanced", "pref_financial_first"))
    M.add("OverlapEF", overlap("pref_esg_first", "pref_financial_first"))

    power = read("power_analysis.csv")
    mde = power.loc[power["test_type"] == "correlation", "min_detectable_effect"].dropna().iloc[0]
    M.add("MDEFull", float(mde), "{:.3f}")


def pre_post(M, u):
    pre = pd.read_csv(PRE / "indexed_data.csv")
    pre = pre[~pre["is_large_cap_benchmark"].fillna(False).astype(bool)]
    j = u[["ticker", "pref_balanced", "ESG_composite", "E_score", "S_score", "G_score"]].merge(
        pre[["ticker", "pref_balanced", "ESG_composite", "E_score", "S_score", "G_score"]],
        on="ticker", suffixes=("", "_pre"))
    M.add("NPrePostCommon", len(j))
    for col, nm in (("pref_balanced", "Bal"), ("ESG_composite", "ESG"), ("E_score", "E"),
                    ("S_score", "S"), ("G_score", "G")):
        M.add(f"RhoPrePost{nm}", float(stats.spearmanr(j[col], j[f"{col}_pre"])[0]), "{:.2f}")
    top_n = get_portfolio_top_n(len(u))
    top_post = set(u.nlargest(top_n, "pref_balanced")["ticker"])
    top_pre = set(pre.nlargest(top_n, "pref_balanced")["ticker"])
    M.add("OverlapPrePost", len(top_post & top_pre))

    boot = read("advanced_bootstrap_ci.csv")
    # The paper previously cited the "enhanced" (Bayesian-bootstrap) intervals.
    pre_boot = read("bootstrap_enhanced_stability.csv", PRE)
    pre_w = (pre_boot["ci_upper"] - pre_boot["ci_lower"])
    M.add("PreCIWidthMedian", float(pre_w.median()), "{:.0f}")
    M.add("PreCIWidthMin", float(pre_w.min()), "{:.0f}")
    M.add("PreNFirmsBoot", len(pre_boot))

    circ = read("circularity_comparison.csv")
    def ins(h, v):
        r = circ[(circ.horizon == h) & (circ.score_variant == v)]
        return float(r["ic_with_market"].iloc[0]) if len(r) else np.nan
    oos = read("oos_information_coefficients.csv")
    def oosic(sig, h="full"):
        r = oos[(oos.signal == sig) & (oos.horizon == h) & (oos.neutralization == "country")]
        return r.iloc[0] if len(r) else None

    lines = ["\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
             "& \\multicolumn{2}{c}{In-sample (pre-snapshot)} & \\multicolumn{2}{c}{Out-of-sample} \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(l){4-5}",
             "Composite & vs.\\ trailing 6m & vs.\\ quality proxy & IC, full window & 95\\% CI \\\\",
             "\\midrule"]
    for sig in ("pref_balanced", "pref_esg_first", "pref_financial_first"):
        o = oosic(sig)
        lines.append(" & ".join([FACTOR_LABELS[sig], fnum(ins("6m", sig)), fnum(ins("quality", sig)),
                                 fnum(o["ic"]) if o is not None else "--",
                                 f"[{fnum(o['ci_low'])}, {fnum(o['ci_high'])}]" if o is not None else "--"]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_insample_vs_oos.tex", "\n".join(lines) + "\n")
    M.add("InSampleICBalSixM", ins("6m", "pref_balanced"), "{:.2f}")
    M.add("InSampleICBalQuality", ins("quality", "pref_balanced"), "{:.2f}")

    # Pre/post audit diagnostic table
    boot_top = boot[boot["original_rank"] <= top_n]
    rows = [
        ("Factors monotonic in quintiles of the quality proxy",
         f"{M_get(M, 'MonoPre')}/{M_get(M, 'MonoTotal')}", f"{M_get(M, 'MonoPost')}/{M_get(M, 'MonoTotal')}"),
        ("Median 95\\% rank-CI width, all firms", f"{pre_w.median():.0f}", f"{boot['ci_width'].median():.0f}"),
        ("Maximum VIF among factor scores", f"{read('vif_multicollinearity.csv', PRE)['VIF'].max():.2f}",
         f"{read('vif_multicollinearity.csv')['VIF'].max():.2f}"),
        (f"Top-{top_n} balanced portfolio: firms in common", "--", f"{len(top_post & top_pre)}/{top_n}"),
        ("Balanced composite: Spearman $\\rho$ pre vs.\\ post", "--",
         f"{stats.spearmanr(j['pref_balanced'], j['pref_balanced_pre'])[0]:.2f}"),
    ]
    oo_pre = oosic("pref_balanced_pre_audit")
    oo_post = oosic("pref_balanced")
    if oo_pre is not None and oo_post is not None:
        rows.append(("Out-of-sample IC of the balanced composite", fnum(oo_pre["ic"]), fnum(oo_post["ic"])))
    lines = ["\\begin{tabular}{@{}p{0.58\\columnwidth}rr@{}}", "\\toprule",
             "Diagnostic & Pre-audit & Post-audit \\\\", "\\midrule"]
    lines += [f"{a} & {b} & {c} \\\\" for a, b, c in rows]
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_pre_post.tex", "\n".join(lines) + "\n")
    _ = boot_top


def M_get(M, name):
    for line in M.lines:
        if line.startswith(f"\\newcommand{{\\{name}}}"):
            return line.split("}{", 1)[1].rsplit("\\xspace", 1)[0]
    raise KeyError(name)


# ---------------------------------------------------------------------------
# Rank uncertainty
# ---------------------------------------------------------------------------
def rank_uncertainty(M, u):
    s = read("bootstrap_rank_uncertainty_summary.csv").iloc[0]
    M.add("BootN", int(s["n_bootstrap"]))
    M.add("BootKappa", f"{s['dirichlet_concentration']:.0f}")
    M.add("BootRecon", float(s["reconstruction_spearman"]), "{:.3f}")
    M.add("CIWidthAll", float(s["median_ci_width_all"]), "{:.0f}")
    M.add("CIWidthTop", float(s["median_ci_width_top_n"]), "{:.0f}")
    M.add("CIWidthTopMax", float(s["max_ci_width_top_n"]), "{:.0f}")
    M.add("CIWidthTopSampling", float(s["median_ci_width_sampling_top_n"]), "{:.0f}")
    M.add("CIWidthTopWeights", float(s["median_ci_width_weights_top_n"]), "{:.0f}")
    M.add("MeanPTop", float(s["mean_p_top_n_of_top_n"]), "{:.2f}")
    M.add("NPTopHalf", int(s["n_top_n_with_p_ge_0_5"]))
    M.add("ExpOverlap", float(s["expected_top_n_overlap"]), "{:.1f}")

    boot = read("advanced_bootstrap_ci.csv")
    top_n = int(s["top_n"])
    info = u.set_index("ticker")[["sector", "country"]]
    oos = read("oos_firm_outcomes.csv").set_index("ticker") if (TABLES / "oos_firm_outcomes.csv").exists() else None
    lines = ["\\begin{tabular}{@{}rllrr r@{}}", "\\toprule",
             "Rank & Ticker & Sector & 95\\% CI & $P(\\text{top-}N)$ & OOS ret.\\ (\\%) \\\\", "\\midrule"]
    for _, r in boot[boot["original_rank"] <= top_n].sort_values("original_rank").iterrows():
        t = r["ticker"]
        sec = info.loc[t, "sector"] if t in info.index else ""
        ret = oos.loc[t, "ret_full"] if oos is not None and t in oos.index else np.nan
        tick = t.replace(".NS", "$^{\\dagger}$").replace("&", "\\&")
        lines.append(f"{int(r['original_rank'])} & {tick} & {sec} & [{r['ci_lower_5']:.0f}, {r['ci_upper_95']:.0f}] "
                     f"& {r['p_top_n']:.2f} & {fnum(ret, '{:.1f}') if pd.notna(ret) else 'exit'} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_top_ranks.tex", "\n".join(lines) + "\n")
    make_rank_figure(boot, top_n)


def make_rank_figure(boot, top_n):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    b = boot.sort_values("original_rank").head(2 * top_n)
    fig, ax = plt.subplots(figsize=(3.4, 3.6))
    y = np.arange(len(b))[::-1]
    ax.hlines(y, b["ci_lower_5"], b["ci_upper_95"], color="#4C72B0", lw=2)
    ax.plot(b["original_rank"], y, "o", color="black", ms=3, label="Point rank")
    ax.axvline(top_n + 0.5, color="#C44E52", ls="--", lw=1, label=f"Top-{top_n} cut-off")
    ax.set_yticks(y)
    ax.set_yticklabels([t.replace(".NS", "*") for t in b["ticker"]], fontsize=5.5)
    ax.set_xlabel("Balanced-profile rank (point and 95% interval)", fontsize=6.5)
    ax.tick_params(axis="x", labelsize=6.5)
    ax.legend(fontsize=6, loc="upper right", frameon=False)
    ax.grid(axis="x", alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_rank_ci.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Out-of-sample
# ---------------------------------------------------------------------------
def oos(M, u):
    meta = read("oos_metadata.csv").iloc[0]
    M.add("NOOS", int(meta["n_with_full_return"]))
    M.add("NExited", int(meta["n_universe"] - meta["n_with_full_return"]))
    M.add("TradingDaysUS", int(meta["trading_days_us"]))
    M.add("TradingDaysIndia", int(meta["trading_days_india"]))
    M.add("UnivRetUS", float(meta["universe_mean_return_us_pct"]), "{:.1f}")
    M.add("UnivRetIndia", float(meta["universe_mean_return_india_pct"]), "{:.1f}")
    if "index_return_us_pct" in meta:
        M.add("IdxRetUS", float(meta["index_return_us_pct"]), "{:.1f}")
        M.add("IdxRetIndia", float(meta["index_return_india_pct"]), "{:.1f}")
    M.add("ESGRSqOOS", float(meta["esg_r2_on_other_factors"]), "{:.2f}")
    M.add("RhoESGVolRaw", float(meta["esg_raw_spearman_with_oos_vol"]), "{:.2f}")
    M.add("RhoVolPersist", float(meta["trailing_vs_oos_vol_spearman"]), "{:.2f}")
    M.add("MDEOOS", float(meta["min_detectable_rho_80pct_power"]), "{:.3f}")

    bounds = read("oos_survivorship_bounds.csv")
    M.add("ExitedTickers", ", ".join(bounds["exited_tickers"].iloc[0].split(";")))
    M.add("ExitedInTop", int(bounds["exited_in_top_n"].iloc[0]))
    M.add("BoundICLow", float(bounds["H1_ic"].min()), "{:.3f}")
    M.add("BoundICHigh", float(bounds["H1_ic"].max()), "{:.3f}")
    M.add("BoundExLow", float(bounds["H3_excess_pp"].min()), "{:.1f}")
    M.add("BoundExHigh", float(bounds["H3_excess_pp"].max()), "{:.1f}")

    prim = read("oos_primary_hypotheses.csv").set_index("hypothesis")
    words = {"H1": "One", "H2": "Two", "H3": "Three"}
    for h, w in words.items():
        r = prim.loc[h]
        f = "{:.1f}" if h == "H3" else "{:.3f}"
        M.add(f"H{w}Est", float(r["estimate"]), f)
        if pd.notna(r["ci_low"]):
            M.add(f"H{w}Lo", float(r["ci_low"]), f)
            M.add(f"H{w}Hi", float(r["ci_high"]), f)
        M.add(f"H{w}P", pval(r["p_one_sided"]))
        M.add(f"H{w}Holm", pval(r["p_holm"]))
    lines = ["\\begin{tabular}{@{}llrcrr@{}}", "\\toprule",
             "& Test & Estimate & 95\\% CI & $p$ & $p_{\\text{Holm}}$ \\\\", "\\midrule"]
    tests = {"H1": "IC of balanced composite with return",
             "H2": "Partial $\\rho$(ESG, realised vol.\\,$\\mid$\\,trailing vol.)",
             "H3": f"Top-{int(meta['top_n'])} minus universe return (pp)"}
    for h in ("H1", "H2", "H3"):
        r = prim.loc[h]
        f = "{:.1f}" if h == "H3" else "{:.3f}"
        ci = "--" if pd.isna(r["ci_low"]) else f"[{fnum(r['ci_low'], f)}, {fnum(r['ci_high'], f)}]"
        lines.append(f"{h} & {tests[h]} & {fnum(r['estimate'], f)} & {ci} & {pval(r['p_one_sided'])} & {pval(r['p_holm'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_oos_primary.tex", "\n".join(lines) + "\n")

    # IC table (country-neutral)
    ic = read("oos_information_coefficients.csv")
    ic = ic[ic["neutralization"] == "country"]
    order = ["ESG_composite", "E_score", "S_score", "G_score", "ESG_orthogonal", "financial_score",
             "operational_score", "risk_adjusted_score", "growth_score", "value_score",
             "stability_score", "market_score", "sector_position", "pref_balanced", "pref_esg_first",
             "pref_financial_first", "pref_equal_weight", "pref_balanced_feb2026",
             "pref_balanced_pre_audit"]
    lines = ["\\begin{tabular}{@{}lrrrc@{}}", "\\toprule",
             "Signal & 1m & 3m & Full & 95\\% CI (full) \\\\", "\\midrule"]
    for sig in order:
        g = ic[ic["signal"] == sig].set_index("horizon")
        if g.empty:
            continue
        if sig == "financial_score" or sig == "pref_balanced":
            lines.append("\\midrule")
        def cell(h):
            if h not in g.index:
                return "--"
            v = fnum(g.loc[h, "ic"])
            return f"\\textbf{{{v}}}" if g.loc[h, "p_holm_within_horizon"] < 0.05 else v
        full = g.loc["full"] if "full" in g.index else None
        ci = f"[{fnum(full['ci_low'])}, {fnum(full['ci_high'])}]" if full is not None else "--"
        lines.append(f"{FACTOR_LABELS.get(sig, sig)} & {cell('1m')} & {cell('3m')} & {cell('full')} & {ci} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_oos_ic.tex", "\n".join(lines) + "\n")
    for sig, nm in (("financial_score", "Fin"), ("S_score", "S"), ("G_score", "G"), ("E_score", "E"),
                    ("ESG_composite", "ESG"), ("pref_esg_first", "ESGFirst"), ("pref_financial_first", "FinFirst"),
                    ("pref_equal_weight", "EqualW"), ("pref_balanced_feb2026", "FebW"),
                    ("pref_balanced_pre_audit", "PreAudit"), ("operational_score", "Op")):
        for h, hn in (("1m", "OneM"), ("full", "Full")):
            r = ic[(ic.signal == sig) & (ic.horizon == h)]
            if len(r):
                M.add(f"IC{nm}{hn}", float(r["ic"].iloc[0]), "{:.3f}")
                M.add(f"ICHolm{nm}{hn}", pval(r["p_holm_within_horizon"].iloc[0]))

    # Portfolio table
    pe = read("oos_portfolio_excess.csv")
    horizons = [h for h in ("1m", "3m", "full", "full_beta_adj", "full_sector_neutral") if h in set(pe["horizon"])]
    hdr = {"1m": "1m", "3m": "3m", "full": "Full", "full_beta_adj": "$\\beta$-adj.",
           "full_sector_neutral": "Sect.-neut."}
    lines = ["\\begin{tabular}{@{}l" + "r" * len(horizons) + "c@{}}", "\\toprule",
             "Top-$N$ by & " + " & ".join(hdr[h] for h in horizons) + " & 95\\% CI (full) \\\\", "\\midrule"]
    for sig in ["pref_balanced", "pref_esg_first", "pref_financial_first", "pref_equal_weight",
                "pref_balanced_feb2026", "pref_balanced_pre_audit", "ESG_composite"]:
        g = pe[pe["signal"] == sig].set_index("horizon")
        if g.empty:
            continue
        cells = [fnum(g.loc[h, "excess_pp"], "{:.1f}") if h in g.index else "--" for h in horizons]
        ci = f"[{fnum(g.loc['full', 'ci_low'], '{:.1f}')}, {fnum(g.loc['full', 'ci_high'], '{:.1f}')}]"
        lines.append(f"{FACTOR_LABELS.get(sig, sig)} & " + " & ".join(cells) + f" & {ci} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_oos_portfolio.tex", "\n".join(lines) + "\n")
    for sig, nm in (("ESG_composite", "ESG"), ("pref_balanced", "Bal"), ("pref_esg_first", "ESGFirst")):
        g = pe[pe["signal"] == sig].set_index("horizon")
        M.add(f"Ex{nm}Full", float(g.loc["full", "excess_pp"]), "{:.1f}")
        M.add(f"Ex{nm}FullLo", float(g.loc["full", "ci_low"]), "{:.1f}")
        M.add(f"Ex{nm}FullHi", float(g.loc["full", "ci_high"]), "{:.1f}")
        if "full_beta_adj" in g.index:
            M.add(f"Ex{nm}BA", float(g.loc["full_beta_adj", "excess_pp"]), "{:.1f}")
            M.add(f"Ex{nm}BALo", float(g.loc["full_beta_adj", "ci_low"]), "{:.1f}")
            M.add(f"Ex{nm}BAHi", float(g.loc["full_beta_adj", "ci_high"]), "{:.1f}")
        if "full_sector_neutral" in g.index:
            M.add(f"Ex{nm}SN", float(g.loc["full_sector_neutral", "excess_pp"]), "{:.1f}")
            M.add(f"Ex{nm}SNLo", float(g.loc["full_sector_neutral", "ci_low"]), "{:.1f}")
            M.add(f"Ex{nm}SNHi", float(g.loc["full_sector_neutral", "ci_high"]), "{:.1f}")

    # Risk filter table
    rf = read("oos_esg_risk_filter.csv")
    rr = read("oos_esg_risk_regression.csv").set_index("esg_measure") if (TABLES / "oos_esg_risk_regression.csv").exists() else None
    lines = ["\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
             "& \\multicolumn{2}{c}{Realised volatility} & Realised $\\beta$ & \\multicolumn{2}{c}{Vol.\\ regression} \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-4}\\cmidrule(l){5-6}",
             "ESG measure & raw $\\rho$ & partial $\\rho$ & partial $\\rho$ & coef. & $p$ \\\\", "\\midrule"]
    for esg in ["ESG_composite", "E_score", "S_score", "G_score", "ESG_orthogonal"]:
        v = rf[(rf.esg_measure == esg) & (rf.outcome == "realized_vol_oos")]
        b = rf[(rf.esg_measure == esg) & (rf.outcome == "realized_beta_oos")]
        if v.empty:
            continue
        v, b = v.iloc[0], b.iloc[0]
        def star(x, p):
            return f"\\textbf{{{fnum(x)}}}" if p < 0.05 else fnum(x)
        reg = rr.loc[esg] if rr is not None and esg in rr.index else None
        lines.append(" & ".join([FACTOR_LABELS[esg], fnum(v["spearman"]),
                                 star(v["partial_spearman"], v["partial_p_holm"]),
                                 star(b["partial_spearman"], b["partial_p_holm"]),
                                 fnum(reg["coef"]) if reg is not None else "--",
                                 pval(reg["p_value"]) if reg is not None else "--"]) + " \\\\")
        tag = {"ESG_composite": "ESG", "E_score": "E", "S_score": "S", "G_score": "G", "ESG_orthogonal": "Orth"}[esg]
        M.add(f"PartVol{tag}", float(v["partial_spearman"]), "{:.3f}")
        M.add(f"PartVolHolm{tag}", pval(v["partial_p_holm"]))
        M.add(f"PartBeta{tag}", float(b["partial_spearman"]), "{:.3f}")
        M.add(f"PartBetaHolm{tag}", pval(b["partial_p_holm"]))
        if reg is not None:
            M.add(f"RegVol{tag}", float(reg["coef"]), "{:.3f}")
            M.add(f"RegVolP{tag}", pval(reg["p_value"]))
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_oos_risk.tex", "\n".join(lines) + "\n")

    reg = read("oos_regression.csv")
    w = reg[(reg.spec == "with_esg")].set_index("variable")
    wo = reg[(reg.spec == "without_esg")]
    M.add("RegESGCoef", float(w.loc["ESG_composite", "coef_pp_per_sd"]), "{:.1f}")
    M.add("RegESGP", pval(w.loc["ESG_composite", "p_value"]))
    M.add("RegRSqWith", float(w["r2"].iloc[0]), "{:.3f}")
    M.add("RegRSqWithout", float(wo["r2"].iloc[0]), "{:.3f}")

    make_ic_figure(read("oos_information_coefficients.csv"))


# ---------------------------------------------------------------------------
# Extensions (step 27) and pre-registration (step 28)
# ---------------------------------------------------------------------------
EXT_LABELS = {"ESG_composite": "ESG composite", "E_score": "\\quad E pillar", "S_score": "\\quad S pillar",
              "G_score": "\\quad G pillar", "ESG_measured": "Measured-cell ESG",
              "ESG_proxy": "Proxy-cell ESG", "ESG_imputed": "Imputed-cell ESG"}


def _coef(r):
    txt = fnum(r["coef"])
    return f"\\textbf{{{txt}}}" if r["p_two_sided"] < 0.05 else txt


def extensions(M):
    ctrl = read("ext_risk_controls.csv")

    def key(o, s, m):
        return ctrl[(ctrl.outcome == o) & (ctrl.spec == s) & (ctrl.esg_measure == m)].iloc[0]

    h4 = key("realized_vol_oos", "full_controls", "ESG_composite")
    ext_spec = importlib.util.spec_from_file_location("ext27", PROJECT_ROOT / "scripts" / "27_paper1_extensions.py")
    ext_mod = importlib.util.module_from_spec(ext_spec)
    ext_spec.loader.exec_module(ext_mod)
    M.add("NControls", len(ext_mod.CONTROLS))
    M.add("HFourEst", float(h4["coef"]))
    M.add("HFourLo", float(h4["ci_low"]))
    M.add("HFourHi", float(h4["ci_high"]))
    M.add("HFourP", pval(h4["p_one_sided_neg"]))
    M.add("HFourPTwo", pval(h4["p_two_sided"]))
    s4 = key("realized_vol_oos", "full_controls", "S_score")
    M.add("HFourS", float(s4["coef"]))
    M.add("HFourSP", pval(s4["p_two_sided"]))
    M.add("HFourG", float(key("realized_vol_oos", "full_controls", "G_score")["coef"]))
    b = key("realized_beta_oos", "full_controls", "ESG_composite")
    M.add("BetaFullESG", float(b["coef"]))
    M.add("BetaFullESGP", pval(b["p_two_sided"]))
    bt = key("realized_beta_oos", "trailing_only", "ESG_composite")
    M.add("BetaTrailESG", float(bt["coef"]))
    M.add("BetaTrailESGP", pval(bt["p_two_sided"]))
    dd = key("max_drawdown_oos", "full_controls", "ESG_composite")
    M.add("DDFullESG", float(dd["coef"]))
    M.add("DDFullESGP", pval(dd["p_two_sided"]))

    lines = ["\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
             "& \\multicolumn{2}{c}{Realised vol.} & \\multicolumn{2}{c}{Realised $\\beta$} & Drawdown \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(l){6-6}",
             "ESG measure & trailing & full & trailing & full & full \\\\", "\\midrule"]
    for m, lab in EXT_LABELS.items():
        if m == "ESG_measured":
            lines.append("\\midrule")
        cells = [_coef(key(o, s, m)) for o, s in (("realized_vol_oos", "trailing_only"),
                                                  ("realized_vol_oos", "full_controls"),
                                                  ("realized_beta_oos", "trailing_only"),
                                                  ("realized_beta_oos", "full_controls"),
                                                  ("max_drawdown_oos", "full_controls"))]
        lines.append(" & ".join([lab] + cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_ext_controls.tex", "\n".join(lines) + "\n")

    prov = read("ext_provenance_split.csv").set_index("measure")
    for m, tag in (("ESG_measured", "Meas"), ("ESG_proxy", "Proxy"), ("ESG_imputed", "Imp")):
        r = prov.loc[m]
        M.add(f"Cells{tag}", float(r["mean_cells_per_firm"]), "{:.1f}")
        M.add(f"RSq{tag}", float(r["r2_on_financial_factors"]), "{:.2f}")
        M.add(f"Part{tag}", float(r["partial_rho_oos_vol"]))
        M.add(f"Part{tag}Lo", float(r["ci_low"]), "{:.2f}")
        M.add(f"Part{tag}Hi", float(r["ci_high"]), "{:.2f}")
        M.add(f"RhoComp{tag}", float(r["spearman_with_esg_composite"]), "{:.2f}")
    M.add("RhoMeasProxy", float(prov["spearman_measured_vs_proxy"].iloc[0]), "{:.2f}")

    cv = read("ext_vol_forecast_cv.csv").set_index("spec")
    M.add("CVBaseRSq", float(cv.loc["baseline_full", "oof_r2_mean"]))
    M.add("CVESGRSq", float(cv.loc["baseline_full+ESG", "oof_r2_mean"]))
    M.add("CVDeltaESG", float(cv.loc["baseline_full+ESG", "delta_vs_baseline_mean"]), "{:.4f}")
    M.add("CVDeltaMeas", float(cv.loc["baseline_full+ESG_measured", "delta_vs_baseline_mean"]), "{:.4f}")
    M.add("CVDeltaProxy", float(cv.loc["baseline_full+ESG_proxy", "delta_vs_baseline_mean"]), "{:.4f}")
    M.add("CVShareImproved", f"{100 * cv.loc['baseline_full+ESG', 'share_repeats_improved']:.0f}")
    M.add("CVRepeats", int(cv["repeats"].iloc[0]))
    M.add("CVFolds", int(cv["folds"].iloc[0]))

    ds = read("ext_double_sort.csv")
    avg = ds[ds["trailing_vol_tercile"].astype(str) == "average"].iloc[0]
    M.add("DSAvg", float(avg["high_minus_low_esg_vol_pp"]), "{:.1f}")
    M.add("DSLo", float(avg["ci_low"]), "{:.1f}")
    M.add("DSHi", float(avg["ci_high"]), "{:.1f}")
    terc = ds[ds["trailing_vol_tercile"].astype(str) != "average"]
    M.add("DSLowTerc", float(terc.iloc[0]["high_minus_low_esg_vol_pp"]), "{:.1f}")
    M.add("DSHighTerc", float(terc.iloc[-1]["high_minus_low_esg_vol_pp"]), "{:.1f}")

    rv = read("ext_recent_vol_control.csv").set_index("control")
    M.add("SplitDate", str(rv["split_date"].iloc[0]))
    r = rv.loc["pre_snapshot_trailing_vol"]
    M.add("RecTrail", float(r["partial_rho_esg_second_half_vol"]))
    M.add("RecTrailLo", float(r["ci_low"]), "{:.2f}")
    M.add("RecTrailHi", float(r["ci_high"]), "{:.2f}")
    r = rv.loc["first_half_realised_vol"]
    M.add("RecFirst", float(r["partial_rho_esg_second_half_vol"]))
    M.add("RecFirstLo", float(r["ci_low"]), "{:.2f}")
    M.add("RecFirstHi", float(r["ci_high"]), "{:.2f}")
    M.add("RecFirstP", pval(r["p_two_sided"]))
    M.add("RecBoth", float(rv.loc["both", "partial_rho_esg_second_half_vol"]))
    M.add("RecBothP", pval(rv.loc["both", "p_two_sided"]))

    rob = read("ext_subsample_robustness.csv")
    pinned = rob.loc[rob["sample"] == "excl. deal-pinned", "excluded_tickers"].fillna("").iloc[0]
    pinned = [t for t in str(pinned).split(";") if t]
    M.add("PinnedTickers", ", ".join(pinned) or "none")
    M.add("NPinned", len(pinned))
    lines = ["\\begin{tabular}{@{}lrcc@{}}", "\\toprule",
             "Sample / test & $N$ & H2 partial $\\rho$ [95\\% CI] & H4 coef.\\ [95\\% CI] \\\\", "\\midrule"]
    for _, r in rob.iterrows():
        h2 = f"{fnum(r['h2_partial_rho'])} [{fnum(r['h2_ci_low'], '{:.2f}')}, {fnum(r['h2_ci_high'], '{:.2f}')}]"
        h4c = f"{fnum(r['h4_coef'])} [{fnum(r['h4_ci_low'], '{:.2f}')}, {fnum(r['h4_ci_high'], '{:.2f}')}]"
        lines.append(f"{r['sample'].replace('&', 'and')} & {int(r['n'])} & {h2} & {h4c} \\\\")
        tag = {"US only": "US", "India only": "India"}.get(r["sample"])
        if tag:
            M.add(f"HTwo{tag}", float(r["h2_partial_rho"]))
            M.add(f"HFour{tag}", float(r["h4_coef"]))
    lines.append("\\midrule")
    for c, lab in (("pre_snapshot_trailing_vol", "2nd-half vol.\\ $\\mid$ pre-snapshot vol."),
                   ("first_half_realised_vol", "2nd-half vol.\\ $\\mid$ 1st-half vol."),
                   ("both", "2nd-half vol.\\ $\\mid$ both")):
        r = rv.loc[c]
        ci = "" if pd.isna(r.get("ci_low")) else f" [{fnum(r['ci_low'], '{:.2f}')}, {fnum(r['ci_high'], '{:.2f}')}]"
        lines.append(f"{lab} & {int(r['n'])} & {fnum(r['partial_rho_esg_second_half_vol'])}{ci} & -- \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_ext_robust.tex", "\n".join(lines) + "\n")

    wu = read("ext_weight_uncertainty.csv").set_index("scheme")
    uni = wu.loc["uniform_simplex"]
    M.add("WDraws", int(uni["draws"]))
    M.add("WICMedian", float(uni["ic_median"]))
    M.add("WICLo", float(uni["ic_p025"]))
    M.add("WICHi", float(uni["ic_p975"]))
    M.add("WSharePos", f"{100 * uni['share_ic_positive']:.1f}")
    M.add("WShareNeg", f"{100 * (1 - uni['share_ic_positive']):.1f}")
    M.add("WShareExPos", f"{100 * uni['share_excess_positive']:.0f}")
    M.add("WShareLowVol", f"{100 * uni['share_topn_lower_vol']:.0f}")
    M.add("WCorrESGIC", float(uni["corr_esg_weight_ic"]), "{:.2f}")
    M.add("WCorrESGVol", float(uni["corr_esg_weight_topn_vol"]), "{:.2f}")
    kap = [i for i in wu.index if i.startswith("dirichlet")][0]
    M.add("WKapSharePos", f"{100 * wu.loc[kap, 'share_ic_positive']:.1f}")
    sw = read("ext_esg_weight_sweep.csv")
    M.add("SweepICZero", float(sw.iloc[0]["ic"]))
    M.add("SweepICOne", float(sw.iloc[-1]["ic"]))
    M.add("SweepVolZero", float(sw.iloc[0]["topn_vol_diff_pp"]), "{:.1f}")

    mon = read("ext_monthly.csv")
    M.add("NMonths", len(mon))
    M.add("MonNegPartial", int((mon["partial_esg_vol_given_trailing"] < 0).sum()))
    M.add("MonNegICBal", int((mon["ic_pref_balanced"] < 0).sum()))
    M.add("MonPartMin", float(mon["partial_esg_vol_given_trailing"].min()))
    M.add("MonPartMax", float(mon["partial_esg_vol_given_trailing"].max()))
    M.add("MonICMin", float(mon["ic_pref_balanced"].min()))
    M.add("MonICMax", float(mon["ic_pref_balanced"].max()))

    cost = read("ext_costs.csv")
    c = cost[(cost.signal == "pref_balanced")].set_index("cost_scenario")
    M.add("CostRT", float(c.loc["base", "round_trip_cost_pp"]), "{:.2f}")
    M.add("CostRTStress", float(c.loc["stress_3x", "round_trip_cost_pp"]), "{:.2f}")
    M.add("NetExBase", float(c.loc["base", "net_excess_vs_universe_pp"]), "{:.1f}")
    M.add("NetExStress", float(c.loc["stress_3x", "net_excess_vs_universe_pp"]), "{:.1f}")
    M.add("NetExIdx", float(c.loc["base", "net_excess_vs_country_index_pp"]), "{:.1f}")
    M.add("CostBpsUS", f"{2 * c.loc['base', 'one_way_bps_us']:.0f}")
    M.add("CostBpsIndia", f"{2 * c.loc['base', 'one_way_bps_india']:.0f}")
    pe = read("oos_portfolio_excess.csv")
    esg_full = pe[(pe.signal == "ESG_composite") & (pe.horizon == "full")]["excess_pp"].iloc[0]
    M.add("ExESGFullAbs", abs(float(esg_full)), "{:.1f}")

    for name in ("fig_ext_weights.pdf", "fig_ext_mechanism.pdf"):
        src = PROJECT_ROOT / "reports" / "figures" / name
        if src.exists():
            shutil.copy(src, FIGS / name)


def preregistration(M):
    d = PROJECT_ROOT / "preregistration" / "window2"
    man = json.loads((d / "manifest.json").read_text(encoding="utf-8"))
    M.add("PreregAnchor", man["anchor"])
    M.add("PreregEnd", man["end"])
    M.add("PreregFrozen", man["frozen_on"])
    dry = pd.read_csv(d / "dry_run_results.csv").set_index("hypothesis")
    M.add("DryAnchor", str(dry["anchor"].iloc[0]))
    M.add("DryEnd", str(dry["end"].iloc[0]))
    M.add("DryHTwo", float(dry.loc["H2", "estimate"]))
    M.add("DryHFour", float(dry.loc["H4", "estimate"]))


def make_overview_figure(n_mid, n_us, n_india, snapshot, oos_end, n_used, n_declared, top_n,
                         prereg_anchor, prereg_end):
    """Figure 1: study design, from public data to the pre-registered window."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch

    fig, ax = plt.subplots(figsize=(7.2, 1.6))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 23)
    ax.axis("off")

    def box(x, y, w, h, title, body, fc, ec):
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.25,rounding_size=1.2",
                                    fc=fc, ec=ec, lw=0.9))
        ax.text(x + w / 2, y + h - 1.6, title, ha="center", va="top", fontsize=6.6, weight="bold")
        ax.text(x + w / 2, y + h - 4.6, body, ha="center", va="top", fontsize=5.6, linespacing=1.25)

    def arrow(x0, x1, y):
        ax.annotate("", xy=(x1, y), xytext=(x0, y),
                    arrowprops=dict(arrowstyle="-|>", lw=0.9, color="#444444"))

    blue, grey, green, orange = ("#e8f0f8", "#1f5a96"), ("#f2f2f2", "#7a7a7a"), \
        ("#e8f4ea", "#1b7837"), ("#fbeee2", "#b35806")
    y, h, w = 7.5, 14.5, 17.5
    xs = [0.5, 20.8, 41.1, 61.4, 81.7]
    box(xs[0], y, w, h, "Public data",
        f"{n_mid} mid-caps\n({n_us} US, {n_india} India)\nYahoo/ISS, SEC XBRL,\nregistries, statements", *grey)
    box(xs[1], y, w, h, "Cell provenance",
        f"{n_used} of {n_declared} ESG indicators\ninformative;\nmeasured / proxy /\nimputed per cell", *grey)
    box(xs[2], y, w, h, "Index",
        f"ESG + 8 financial\nfactors, 3 profiles,\nrank aggregation,\ntop-{top_n} portfolio", *blue)
    box(xs[3], y, w, h, "Window 1 (OOS)",
        f"freeze {snapshot}\n→ {oos_end}\nH1–H3 fixed, Holm;\nH4 + mechanism", *green)
    box(xs[4], y, w, h, "Window 2 (registered)",
        f"{prereg_anchor}\n→ {prereg_end}\nhashed scores, plan\nand code; H1–H4", *orange)
    for a, b in zip(xs[:-1], xs[1:]):
        arrow(a + w + 0.4, b - 0.4, y + h / 2)

    # Research questions under the stages they address
    rq = [(xs[1], "RQ1  what does the\nESG score measure?"),
          (xs[2], "RQ2  does in-sample\nvalidation mislead?"),
          (xs[3], "RQ3  prediction out of sample\nRQ4  where the risk signal lives")]
    for x, t in rq:
        ax.text(x + w / 2, 5.6, t, ha="center", va="top", fontsize=5.8, style="italic", color="#333333")
    plt.tight_layout(pad=0.1)
    FIGS.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGS / "fig_overview.pdf")
    fig.savefig(PROJECT_ROOT / "reports" / "figures" / "fig_overview.png", dpi=200)
    plt.close(fig)


def make_ic_figure(ic):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ic = ic[(ic["neutralization"] == "country") & (ic["horizon"] == "full")].set_index("signal")
    order = ["pref_balanced", "pref_esg_first", "pref_financial_first", "pref_equal_weight",
             "pref_balanced_feb2026", "pref_balanced_pre_audit", "ESG_composite", "E_score",
             "S_score", "G_score", "ESG_orthogonal", "financial_score", "operational_score",
             "risk_adjusted_score", "growth_score", "value_score", "stability_score",
             "sector_position", "market_score"]
    order = [o for o in order if o in ic.index]
    fig, ax = plt.subplots(figsize=(3.4, 3.9))
    y = np.arange(len(order))[::-1]
    for yi, sig in zip(y, order):
        r = ic.loc[sig]
        colour = "#1f4e8c" if sig.startswith("pref_") else ("#2e7d32" if sig in
                 ("ESG_composite", "E_score", "S_score", "G_score", "ESG_orthogonal") else "#666666")
        ax.hlines(yi, r["ci_low"], r["ci_high"], color=colour, lw=1.4, alpha=0.8)
        ax.plot(r["ic"], yi, "o", color=colour, ms=3.5)
    ax.axvline(0, color="black", lw=0.8)
    ax.set_yticks(y)
    ax.set_yticklabels([FACTOR_LABELS.get(s, s).replace(r"\quad ", "  ").replace(r"$\perp$", "orth.")
                        .replace(" (not weighted)", "*") for s in order], fontsize=6)
    ax.set_xlabel("Rank IC with country-neutral return (95% CI)", fontsize=6.5)
    ax.tick_params(axis="x", labelsize=6.5)
    ax.grid(axis="x", alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_oos_ic.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Method tables from config
# ---------------------------------------------------------------------------
def weight_table(M):
    profiles = {p: load_profile_weights(p) for p in ("esg_first", "balanced", "financial_first")}
    rows = ["ESG_composite", "financial_score", "risk_adjusted_score", "growth_score",
            "stability_score", "sector_position", "operational_score", "value_score", "market_score"]
    eff = {}
    for p, w in profiles.items():
        w = {k: v for k, v in w.items() if k != "similarity_rank"}
        nm = {k: v for k, v in w.items() if k != "market_score"}
        tot = sum(nm.values())
        eff[p] = {k: (v / tot if k != "market_score" else 0.0) for k, v in w.items()}
        eff[p]["_raw_market"] = w.get("market_score", 0.0)
    lines = ["\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
             "Factor & ESG-first & Balanced & Financial-first \\\\", "\\midrule"]
    for k in rows:
        lines.append(f"{FACTOR_LABELS[k].replace(' (not weighted)', '')} & " +
                     " & ".join(f"{100 * eff[p].get(k, 0):.1f}" for p in profiles) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_weights.tex", "\n".join(lines) + "\n")
    M.add("WBalESG", f"{100 * eff['balanced']['ESG_composite']:.1f}")
    M.add("WESGFirstESG", f"{100 * eff['esg_first']['ESG_composite']:.1f}")
    M.add("WFinFirstESG", f"{100 * eff['financial_first']['ESG_composite']:.1f}")

    sasb = yaml.safe_load((PROJECT_ROOT / "config" / "sasb_materiality.yaml").read_text(encoding="utf-8"))
    sm = sasb["sector_materiality"]
    lines = ["\\begin{tabular}{@{}lrrr@{}}", "\\toprule", "Sector & E & S & G \\\\", "\\midrule"]
    for sec, w in sm.items():
        if sec == "default":
            continue
        lines.append(f"{sec} & {w['E']:.2f} & {w['S']:.2f} & {w['G']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write_table("tab_sasb.tex", "\n".join(lines) + "\n")


def copy_figures():
    for name in ("fig03_correlation_heatmap.png",):
        src = PROJECT_ROOT / "reports" / "figures" / name
        if src.exists():
            shutil.copy(src, FIGS / name)


def main():
    print("=" * 70)
    print("STEP 26: PAPER ARTIFACTS (numbers.tex, tables, figures)")
    print("=" * 70)
    GEN.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)
    cfg = yaml.safe_load((PROJECT_ROOT / "config" / "index_config.yaml").read_text(encoding="utf-8"))
    cfg.setdefault("INR_USD", find_fx(cfg))
    df = pd.read_csv(PROCESSED / "indexed_data.csv")
    u = df[~df["is_large_cap_benchmark"].fillna(False).astype(bool)].copy()

    M = Macros()
    sample_numbers(M, df, u, cfg)
    provenance(M, u)
    esg_redundancy(M, u)
    diagnostics(M, u)
    oos(M, u)
    pre_post(M, u)
    rank_uncertainty(M, u)
    extensions(M)
    preregistration(M)
    g = lambda k: M_get(M, k)
    make_overview_figure(g("NMid"), g("NUS"), g("NIndia"), g("SnapshotDate"), g("OOSEndDate"),
                         g("NIndUsed"), g("NIndDeclared"), g("TopN"), g("PreregAnchor"), g("PreregEnd"))
    weight_table(M)
    copy_figures()
    M.write(GEN / "numbers.tex")
    print(f"  [OK] {len(M.names)} macros -> {GEN / 'numbers.tex'}")
    print(f"  [OK] tables: {sorted(p.name for p in GEN.glob('tab_*.tex'))}")


if __name__ == "__main__":
    main()
